-e name: terraform

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: terraform init
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
      - name: terraform validate
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
        run: |
          terraform --version
          terraform fmt -check
          terraform validate

